title: Inkub.us
default_lang: fr
author:
  name: 'Différents auteurs'
  email: info@inkub.us
taxonomies:
  - category
  - tag
metadata:
  description: 'RTFM Skeleton'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
